/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ClusterInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Information about a set of Elasticsearch clusters, multiple Kibana instance, or multiple APM Servers.
 */
@Schema(description = "Information about a set of Elasticsearch clusters, multiple Kibana instance, or multiple APM Servers.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class ClustersInfo {
  @SerializedName("return_count")
  private Integer returnCount = null;

  @SerializedName("match_count")
  private Integer matchCount = null;

  @SerializedName("clusters")
  private List<ClusterInfo> clusters = new ArrayList<ClusterInfo>();

  public ClustersInfo returnCount(Integer returnCount) {
    this.returnCount = returnCount;
    return this;
  }

   /**
   * The number of clusters actually returned
   * @return returnCount
  **/
  @Schema(required = true, description = "The number of clusters actually returned")
  public Integer getReturnCount() {
    return returnCount;
  }

  public void setReturnCount(Integer returnCount) {
    this.returnCount = returnCount;
  }

  public ClustersInfo matchCount(Integer matchCount) {
    this.matchCount = matchCount;
    return this;
  }

   /**
   * If a query is supplied, then the total number of clusters that matched
   * @return matchCount
  **/
  @Schema(description = "If a query is supplied, then the total number of clusters that matched")
  public Integer getMatchCount() {
    return matchCount;
  }

  public void setMatchCount(Integer matchCount) {
    this.matchCount = matchCount;
  }

  public ClustersInfo clusters(List<ClusterInfo> clusters) {
    this.clusters = clusters;
    return this;
  }

  public ClustersInfo addClustersItem(ClusterInfo clustersItem) {
    this.clusters.add(clustersItem);
    return this;
  }

   /**
   * Get clusters
   * @return clusters
  **/
  @Schema(required = true, description = "")
  public List<ClusterInfo> getClusters() {
    return clusters;
  }

  public void setClusters(List<ClusterInfo> clusters) {
    this.clusters = clusters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClustersInfo clustersInfo = (ClustersInfo) o;
    return Objects.equals(this.returnCount, clustersInfo.returnCount) &&
        Objects.equals(this.matchCount, clustersInfo.matchCount) &&
        Objects.equals(this.clusters, clustersInfo.clusters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(returnCount, matchCount, clusters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClustersInfo {\n");
    
    sb.append("    returnCount: ").append(toIndentedString(returnCount)).append("\n");
    sb.append("    matchCount: ").append(toIndentedString(matchCount)).append("\n");
    sb.append("    clusters: ").append(toIndentedString(clusters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
