/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The static object for the Elasticsearch cluster snapshot repository.
 */
@Schema(description = "The static object for the Elasticsearch cluster snapshot repository.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class ClusterSnapshotRepositoryStatic {
  @SerializedName("repository_type")
  private String repositoryType = null;

  @SerializedName("settings")
  private Object settings = null;

  public ClusterSnapshotRepositoryStatic repositoryType(String repositoryType) {
    this.repositoryType = repositoryType;
    return this;
  }

   /**
   * Type of snapshot repository, ie: S3
   * @return repositoryType
  **/
  @Schema(description = "Type of snapshot repository, ie: S3")
  public String getRepositoryType() {
    return repositoryType;
  }

  public void setRepositoryType(String repositoryType) {
    this.repositoryType = repositoryType;
  }

  public ClusterSnapshotRepositoryStatic settings(Object settings) {
    this.settings = settings;
    return this;
  }

   /**
   * Settings associated with snapshot repository
   * @return settings
  **/
  @Schema(description = "Settings associated with snapshot repository")
  public Object getSettings() {
    return settings;
  }

  public void setSettings(Object settings) {
    this.settings = settings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterSnapshotRepositoryStatic clusterSnapshotRepositoryStatic = (ClusterSnapshotRepositoryStatic) o;
    return Objects.equals(this.repositoryType, clusterSnapshotRepositoryStatic.repositoryType) &&
        Objects.equals(this.settings, clusterSnapshotRepositoryStatic.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(repositoryType, settings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterSnapshotRepositoryStatic {\n");
    
    sb.append("    repositoryType: ").append(toIndentedString(repositoryType)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
