/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ClusterInstanceInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The topology for Elasticsearch clusters, multiple Kibana instances, or multiple APM Servers. The &#x60;ClusterTopologyInfo&#x60; also includes the instances and containers, and where they are located.
 */
@Schema(description = "The topology for Elasticsearch clusters, multiple Kibana instances, or multiple APM Servers. The `ClusterTopologyInfo` also includes the instances and containers, and where they are located.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class ClusterTopologyInfo {
  @SerializedName("healthy")
  private Boolean healthy = null;

  @SerializedName("instances")
  private List<ClusterInstanceInfo> instances = new ArrayList<ClusterInstanceInfo>();

  public ClusterTopologyInfo healthy(Boolean healthy) {
    this.healthy = healthy;
    return this;
  }

   /**
   * Whether the cluster topology is healthy (ie all instances are started and the services they run - ie elasticsearch - are available
   * @return healthy
  **/
  @Schema(required = true, description = "Whether the cluster topology is healthy (ie all instances are started and the services they run - ie elasticsearch - are available")
  public Boolean isHealthy() {
    return healthy;
  }

  public void setHealthy(Boolean healthy) {
    this.healthy = healthy;
  }

  public ClusterTopologyInfo instances(List<ClusterInstanceInfo> instances) {
    this.instances = instances;
    return this;
  }

  public ClusterTopologyInfo addInstancesItem(ClusterInstanceInfo instancesItem) {
    this.instances.add(instancesItem);
    return this;
  }

   /**
   * Get instances
   * @return instances
  **/
  @Schema(required = true, description = "")
  public List<ClusterInstanceInfo> getInstances() {
    return instances;
  }

  public void setInstances(List<ClusterInstanceInfo> instances) {
    this.instances = instances;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterTopologyInfo clusterTopologyInfo = (ClusterTopologyInfo) o;
    return Objects.equals(this.healthy, clusterTopologyInfo.healthy) &&
        Objects.equals(this.instances, clusterTopologyInfo.instances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(healthy, instances);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterTopologyInfo {\n");
    
    sb.append("    healthy: ").append(toIndentedString(healthy)).append("\n");
    sb.append("    instances: ").append(toIndentedString(instances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
