/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ContainersEntryOptionsContainerConfig;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Overrides for the container allocation.
 */
@Schema(description = "Overrides for the container allocation.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class ContainersEntryOptionsOverrides {
  @SerializedName("container_config")
  private ContainersEntryOptionsContainerConfig containerConfig = null;

  public ContainersEntryOptionsOverrides containerConfig(ContainersEntryOptionsContainerConfig containerConfig) {
    this.containerConfig = containerConfig;
    return this;
  }

   /**
   * Get containerConfig
   * @return containerConfig
  **/
  @Schema(description = "")
  public ContainersEntryOptionsContainerConfig getContainerConfig() {
    return containerConfig;
  }

  public void setContainerConfig(ContainersEntryOptionsContainerConfig containerConfig) {
    this.containerConfig = containerConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContainersEntryOptionsOverrides containersEntryOptionsOverrides = (ContainersEntryOptionsOverrides) o;
    return Objects.equals(this.containerConfig, containersEntryOptionsOverrides.containerConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(containerConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContainersEntryOptionsOverrides {\n");
    
    sb.append("    containerConfig: ").append(toIndentedString(containerConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
