/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DeploymentDiagnostics;
import io.swagger.client.model.DeploymentResource;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * A response returned from the Deployment create endpoint
 */
@Schema(description = "A response returned from the Deployment create endpoint")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class DeploymentCreateResponse {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("created")
  private Boolean created = null;

  @SerializedName("resources")
  private List<DeploymentResource> resources = new ArrayList<DeploymentResource>();

  @SerializedName("diagnostics")
  private DeploymentDiagnostics diagnostics = null;

  public DeploymentCreateResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The id of the deployment
   * @return id
  **/
  @Schema(required = true, description = "The id of the deployment")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DeploymentCreateResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the deployment
   * @return name
  **/
  @Schema(required = true, description = "The name of the deployment")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DeploymentCreateResponse created(Boolean created) {
    this.created = created;
    return this;
  }

   /**
   * Whether or not the deployment was freshly created
   * @return created
  **/
  @Schema(required = true, description = "Whether or not the deployment was freshly created")
  public Boolean isCreated() {
    return created;
  }

  public void setCreated(Boolean created) {
    this.created = created;
  }

  public DeploymentCreateResponse resources(List<DeploymentResource> resources) {
    this.resources = resources;
    return this;
  }

  public DeploymentCreateResponse addResourcesItem(DeploymentResource resourcesItem) {
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * List of created resources.
   * @return resources
  **/
  @Schema(required = true, description = "List of created resources.")
  public List<DeploymentResource> getResources() {
    return resources;
  }

  public void setResources(List<DeploymentResource> resources) {
    this.resources = resources;
  }

  public DeploymentCreateResponse diagnostics(DeploymentDiagnostics diagnostics) {
    this.diagnostics = diagnostics;
    return this;
  }

   /**
   * Get diagnostics
   * @return diagnostics
  **/
  @Schema(description = "")
  public DeploymentDiagnostics getDiagnostics() {
    return diagnostics;
  }

  public void setDiagnostics(DeploymentDiagnostics diagnostics) {
    this.diagnostics = diagnostics;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeploymentCreateResponse deploymentCreateResponse = (DeploymentCreateResponse) o;
    return Objects.equals(this.id, deploymentCreateResponse.id) &&
        Objects.equals(this.name, deploymentCreateResponse.name) &&
        Objects.equals(this.created, deploymentCreateResponse.created) &&
        Objects.equals(this.resources, deploymentCreateResponse.resources) &&
        Objects.equals(this.diagnostics, deploymentCreateResponse.diagnostics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, created, resources, diagnostics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeploymentCreateResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    diagnostics: ").append(toIndentedString(diagnostics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
