/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The container for an IP filter rule.
 */
@Schema(description = "The container for an IP filter rule.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class IpFilterRule {
  @SerializedName("id")
  private String id = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("source")
  private String source = null;

  public IpFilterRule id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The rule ID
   * @return id
  **/
  @Schema(description = "The rule ID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public IpFilterRule description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the rule
   * @return description
  **/
  @Schema(description = "Description of the rule")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public IpFilterRule source(String source) {
    this.source = source;
    return this;
  }

   /**
   * IPV4, IPV6 address or CIDR mask to define single or range of IPs
   * @return source
  **/
  @Schema(required = true, description = "IPV4, IPV6 address or CIDR mask to define single or range of IPs")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IpFilterRule ipFilterRule = (IpFilterRule) o;
    return Objects.equals(this.id, ipFilterRule.id) &&
        Objects.equals(this.description, ipFilterRule.description) &&
        Objects.equals(this.source, ipFilterRule.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, description, source);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IpFilterRule {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
