/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.KibanaClusterInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Describes an Kibana resource belonging to a Deployment
 */
@Schema(description = "Describes an Kibana resource belonging to a Deployment")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class KibanaResourceInfo {
  @SerializedName("ref_id")
  private String refId = null;

  @SerializedName("elasticsearch_cluster_ref_id")
  private String elasticsearchClusterRefId = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("region")
  private String region = null;

  @SerializedName("info")
  private KibanaClusterInfo info = null;

  public KibanaResourceInfo refId(String refId) {
    this.refId = refId;
    return this;
  }

   /**
   * The locally-unique user-specified id of a Resource
   * @return refId
  **/
  @Schema(required = true, description = "The locally-unique user-specified id of a Resource")
  public String getRefId() {
    return refId;
  }

  public void setRefId(String refId) {
    this.refId = refId;
  }

  public KibanaResourceInfo elasticsearchClusterRefId(String elasticsearchClusterRefId) {
    this.elasticsearchClusterRefId = elasticsearchClusterRefId;
    return this;
  }

   /**
   * The Elasticsearch cluster that this resource depends on.
   * @return elasticsearchClusterRefId
  **/
  @Schema(required = true, description = "The Elasticsearch cluster that this resource depends on.")
  public String getElasticsearchClusterRefId() {
    return elasticsearchClusterRefId;
  }

  public void setElasticsearchClusterRefId(String elasticsearchClusterRefId) {
    this.elasticsearchClusterRefId = elasticsearchClusterRefId;
  }

  public KibanaResourceInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The randomly-generated id of a Resource
   * @return id
  **/
  @Schema(required = true, description = "The randomly-generated id of a Resource")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public KibanaResourceInfo region(String region) {
    this.region = region;
    return this;
  }

   /**
   * The region where this resource exists
   * @return region
  **/
  @Schema(required = true, description = "The region where this resource exists")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public KibanaResourceInfo info(KibanaClusterInfo info) {
    this.info = info;
    return this;
  }

   /**
   * Get info
   * @return info
  **/
  @Schema(required = true, description = "")
  public KibanaClusterInfo getInfo() {
    return info;
  }

  public void setInfo(KibanaClusterInfo info) {
    this.info = info;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KibanaResourceInfo kibanaResourceInfo = (KibanaResourceInfo) o;
    return Objects.equals(this.refId, kibanaResourceInfo.refId) &&
        Objects.equals(this.elasticsearchClusterRefId, kibanaResourceInfo.elasticsearchClusterRefId) &&
        Objects.equals(this.id, kibanaResourceInfo.id) &&
        Objects.equals(this.region, kibanaResourceInfo.region) &&
        Objects.equals(this.info, kibanaResourceInfo.info);
  }

  @Override
  public int hashCode() {
    return Objects.hash(refId, elasticsearchClusterRefId, id, region, info);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KibanaResourceInfo {\n");
    
    sb.append("    refId: ").append(toIndentedString(refId)).append("\n");
    sb.append("    elasticsearchClusterRefId: ").append(toIndentedString(elasticsearchClusterRefId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
