/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.LicenseInfo;
import io.swagger.client.model.UsageStats;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The container for a license.
 */
@Schema(description = "The container for a license.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class LicenseObject {
  @SerializedName("license")
  private LicenseInfo license = null;

  @SerializedName("usage_stats")
  private UsageStats usageStats = null;

  public LicenseObject license(LicenseInfo license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  @Schema(required = true, description = "")
  public LicenseInfo getLicense() {
    return license;
  }

  public void setLicense(LicenseInfo license) {
    this.license = license;
  }

  public LicenseObject usageStats(UsageStats usageStats) {
    this.usageStats = usageStats;
    return this;
  }

   /**
   * Get usageStats
   * @return usageStats
  **/
  @Schema(description = "")
  public UsageStats getUsageStats() {
    return usageStats;
  }

  public void setUsageStats(UsageStats usageStats) {
    this.usageStats = usageStats;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenseObject licenseObject = (LicenseObject) o;
    return Objects.equals(this.license, licenseObject.license) &&
        Objects.equals(this.usageStats, licenseObject.usageStats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(license, usageStats);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenseObject {\n");
    
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    usageStats: ").append(toIndentedString(usageStats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
