/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.TransientApmPlanConfiguration;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The configuration object for moving APM Servers.
 */
@Schema(description = "The configuration object for moving APM Servers.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class MoveApmClusterConfiguration {
  @SerializedName("cluster_ids")
  private List<String> clusterIds = new ArrayList<String>();

  @SerializedName("plan_override")
  private TransientApmPlanConfiguration planOverride = null;

  public MoveApmClusterConfiguration clusterIds(List<String> clusterIds) {
    this.clusterIds = clusterIds;
    return this;
  }

  public MoveApmClusterConfiguration addClusterIdsItem(String clusterIdsItem) {
    this.clusterIds.add(clusterIdsItem);
    return this;
  }

   /**
   * Identifiers for the Apm clusters.
   * @return clusterIds
  **/
  @Schema(required = true, description = "Identifiers for the Apm clusters.")
  public List<String> getClusterIds() {
    return clusterIds;
  }

  public void setClusterIds(List<String> clusterIds) {
    this.clusterIds = clusterIds;
  }

  public MoveApmClusterConfiguration planOverride(TransientApmPlanConfiguration planOverride) {
    this.planOverride = planOverride;
    return this;
  }

   /**
   * Get planOverride
   * @return planOverride
  **/
  @Schema(description = "")
  public TransientApmPlanConfiguration getPlanOverride() {
    return planOverride;
  }

  public void setPlanOverride(TransientApmPlanConfiguration planOverride) {
    this.planOverride = planOverride;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MoveApmClusterConfiguration moveApmClusterConfiguration = (MoveApmClusterConfiguration) o;
    return Objects.equals(this.clusterIds, moveApmClusterConfiguration.clusterIds) &&
        Objects.equals(this.planOverride, moveApmClusterConfiguration.planOverride);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clusterIds, planOverride);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MoveApmClusterConfiguration {\n");
    
    sb.append("    clusterIds: ").append(toIndentedString(clusterIds)).append("\n");
    sb.append("    planOverride: ").append(toIndentedString(planOverride)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
