/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.MoveApmClusterDetails;
import io.swagger.client.model.MoveAppSearchDetails;
import io.swagger.client.model.MoveElasticsearchClusterDetails;
import io.swagger.client.model.MoveKibanaClusterDetails;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Information about the Elasticsearch clusters, multiple Kibana instances, and multiple APM Servers that are moved off of the allocator.
 */
@Schema(description = "Information about the Elasticsearch clusters, multiple Kibana instances, and multiple APM Servers that are moved off of the allocator.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class MoveClustersDetails {
  @SerializedName("elasticsearch_clusters")
  private List<MoveElasticsearchClusterDetails> elasticsearchClusters = null;

  @SerializedName("kibana_clusters")
  private List<MoveKibanaClusterDetails> kibanaClusters = null;

  @SerializedName("apm_clusters")
  private List<MoveApmClusterDetails> apmClusters = null;

  @SerializedName("appsearch_clusters")
  private List<MoveAppSearchDetails> appsearchClusters = null;

  public MoveClustersDetails elasticsearchClusters(List<MoveElasticsearchClusterDetails> elasticsearchClusters) {
    this.elasticsearchClusters = elasticsearchClusters;
    return this;
  }

  public MoveClustersDetails addElasticsearchClustersItem(MoveElasticsearchClusterDetails elasticsearchClustersItem) {
    if (this.elasticsearchClusters == null) {
      this.elasticsearchClusters = new ArrayList<MoveElasticsearchClusterDetails>();
    }
    this.elasticsearchClusters.add(elasticsearchClustersItem);
    return this;
  }

   /**
   * Detailed information about the Elasticsearch clusters being moved.
   * @return elasticsearchClusters
  **/
  @Schema(description = "Detailed information about the Elasticsearch clusters being moved.")
  public List<MoveElasticsearchClusterDetails> getElasticsearchClusters() {
    return elasticsearchClusters;
  }

  public void setElasticsearchClusters(List<MoveElasticsearchClusterDetails> elasticsearchClusters) {
    this.elasticsearchClusters = elasticsearchClusters;
  }

  public MoveClustersDetails kibanaClusters(List<MoveKibanaClusterDetails> kibanaClusters) {
    this.kibanaClusters = kibanaClusters;
    return this;
  }

  public MoveClustersDetails addKibanaClustersItem(MoveKibanaClusterDetails kibanaClustersItem) {
    if (this.kibanaClusters == null) {
      this.kibanaClusters = new ArrayList<MoveKibanaClusterDetails>();
    }
    this.kibanaClusters.add(kibanaClustersItem);
    return this;
  }

   /**
   * Detailed information about the Kibana clusters being moved.
   * @return kibanaClusters
  **/
  @Schema(description = "Detailed information about the Kibana clusters being moved.")
  public List<MoveKibanaClusterDetails> getKibanaClusters() {
    return kibanaClusters;
  }

  public void setKibanaClusters(List<MoveKibanaClusterDetails> kibanaClusters) {
    this.kibanaClusters = kibanaClusters;
  }

  public MoveClustersDetails apmClusters(List<MoveApmClusterDetails> apmClusters) {
    this.apmClusters = apmClusters;
    return this;
  }

  public MoveClustersDetails addApmClustersItem(MoveApmClusterDetails apmClustersItem) {
    if (this.apmClusters == null) {
      this.apmClusters = new ArrayList<MoveApmClusterDetails>();
    }
    this.apmClusters.add(apmClustersItem);
    return this;
  }

   /**
   * Detailed information about the Apm clusters being moved.
   * @return apmClusters
  **/
  @Schema(description = "Detailed information about the Apm clusters being moved.")
  public List<MoveApmClusterDetails> getApmClusters() {
    return apmClusters;
  }

  public void setApmClusters(List<MoveApmClusterDetails> apmClusters) {
    this.apmClusters = apmClusters;
  }

  public MoveClustersDetails appsearchClusters(List<MoveAppSearchDetails> appsearchClusters) {
    this.appsearchClusters = appsearchClusters;
    return this;
  }

  public MoveClustersDetails addAppsearchClustersItem(MoveAppSearchDetails appsearchClustersItem) {
    if (this.appsearchClusters == null) {
      this.appsearchClusters = new ArrayList<MoveAppSearchDetails>();
    }
    this.appsearchClusters.add(appsearchClustersItem);
    return this;
  }

   /**
   * Detailed information about the App Search clusters being moved.
   * @return appsearchClusters
  **/
  @Schema(description = "Detailed information about the App Search clusters being moved.")
  public List<MoveAppSearchDetails> getAppsearchClusters() {
    return appsearchClusters;
  }

  public void setAppsearchClusters(List<MoveAppSearchDetails> appsearchClusters) {
    this.appsearchClusters = appsearchClusters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MoveClustersDetails moveClustersDetails = (MoveClustersDetails) o;
    return Objects.equals(this.elasticsearchClusters, moveClustersDetails.elasticsearchClusters) &&
        Objects.equals(this.kibanaClusters, moveClustersDetails.kibanaClusters) &&
        Objects.equals(this.apmClusters, moveClustersDetails.apmClusters) &&
        Objects.equals(this.appsearchClusters, moveClustersDetails.appsearchClusters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(elasticsearchClusters, kibanaClusters, apmClusters, appsearchClusters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MoveClustersDetails {\n");
    
    sb.append("    elasticsearchClusters: ").append(toIndentedString(elasticsearchClusters)).append("\n");
    sb.append("    kibanaClusters: ").append(toIndentedString(kibanaClusters)).append("\n");
    sb.append("    apmClusters: ").append(toIndentedString(apmClusters)).append("\n");
    sb.append("    appsearchClusters: ").append(toIndentedString(appsearchClusters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
