/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BasicFailedReplyElement;
import io.swagger.client.model.TransientKibanaPlanConfiguration;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Information about the Kibana instance that you want to move.
 */
@Schema(description = "Information about the Kibana instance that you want to move.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class MoveKibanaClusterDetails {
  @SerializedName("cluster_id")
  private String clusterId = null;

  @SerializedName("calculated_plan")
  private TransientKibanaPlanConfiguration calculatedPlan = null;

  @SerializedName("errors")
  private List<BasicFailedReplyElement> errors = null;

  public MoveKibanaClusterDetails clusterId(String clusterId) {
    this.clusterId = clusterId;
    return this;
  }

   /**
   * Identifier for the Kibana cluster.
   * @return clusterId
  **/
  @Schema(required = true, description = "Identifier for the Kibana cluster.")
  public String getClusterId() {
    return clusterId;
  }

  public void setClusterId(String clusterId) {
    this.clusterId = clusterId;
  }

  public MoveKibanaClusterDetails calculatedPlan(TransientKibanaPlanConfiguration calculatedPlan) {
    this.calculatedPlan = calculatedPlan;
    return this;
  }

   /**
   * Get calculatedPlan
   * @return calculatedPlan
  **/
  @Schema(description = "")
  public TransientKibanaPlanConfiguration getCalculatedPlan() {
    return calculatedPlan;
  }

  public void setCalculatedPlan(TransientKibanaPlanConfiguration calculatedPlan) {
    this.calculatedPlan = calculatedPlan;
  }

  public MoveKibanaClusterDetails errors(List<BasicFailedReplyElement> errors) {
    this.errors = errors;
    return this;
  }

  public MoveKibanaClusterDetails addErrorsItem(BasicFailedReplyElement errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<BasicFailedReplyElement>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * A list of errors that occurred if the attempt to move the cluster failed.
   * @return errors
  **/
  @Schema(description = "A list of errors that occurred if the attempt to move the cluster failed.")
  public List<BasicFailedReplyElement> getErrors() {
    return errors;
  }

  public void setErrors(List<BasicFailedReplyElement> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MoveKibanaClusterDetails moveKibanaClusterDetails = (MoveKibanaClusterDetails) o;
    return Objects.equals(this.clusterId, moveKibanaClusterDetails.clusterId) &&
        Objects.equals(this.calculatedPlan, moveKibanaClusterDetails.calculatedPlan) &&
        Objects.equals(this.errors, moveKibanaClusterDetails.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clusterId, calculatedPlan, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MoveKibanaClusterDetails {\n");
    
    sb.append("    clusterId: ").append(toIndentedString(clusterId)).append("\n");
    sb.append("    calculatedPlan: ").append(toIndentedString(calculatedPlan)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
