/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Value used to bind to a port on the host.
 */
@Schema(description = "Value used to bind to a port on the host.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class PortBinding {
  @SerializedName("host_port")
  private String hostPort = null;

  @SerializedName("host_ip")
  private String hostIp = null;

  public PortBinding hostPort(String hostPort) {
    this.hostPort = hostPort;
    return this;
  }

   /**
   * Port as observed by the host.
   * @return hostPort
  **/
  @Schema(required = true, description = "Port as observed by the host.")
  public String getHostPort() {
    return hostPort;
  }

  public void setHostPort(String hostPort) {
    this.hostPort = hostPort;
  }

  public PortBinding hostIp(String hostIp) {
    this.hostIp = hostIp;
    return this;
  }

   /**
   * IP to bind to on the host. I.e {@code 0.0.0.0}
   * @return hostIp
  **/
  @Schema(example = "0.0.0.0", description = "IP to bind to on the host. I.e {@code 0.0.0.0}")
  public String getHostIp() {
    return hostIp;
  }

  public void setHostIp(String hostIp) {
    this.hostIp = hostIp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PortBinding portBinding = (PortBinding) o;
    return Objects.equals(this.hostPort, portBinding.hostPort) &&
        Objects.equals(this.hostIp, portBinding.hostIp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hostPort, hostIp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PortBinding {\n");
    
    sb.append("    hostPort: ").append(toIndentedString(hostPort)).append("\n");
    sb.append("    hostIp: ").append(toIndentedString(hostIp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
