/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The number of proxy allocations.
 */
@Schema(description = "The number of proxy allocations.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class ProxyAllocationCounts {
  @SerializedName("allocations")
  private Integer allocations = null;

  @SerializedName("connectors")
  private Integer connectors = null;

  public ProxyAllocationCounts allocations(Integer allocations) {
    this.allocations = allocations;
    return this;
  }

   /**
   * The allocations count.
   * @return allocations
  **/
  @Schema(required = true, description = "The allocations count.")
  public Integer getAllocations() {
    return allocations;
  }

  public void setAllocations(Integer allocations) {
    this.allocations = allocations;
  }

  public ProxyAllocationCounts connectors(Integer connectors) {
    this.connectors = connectors;
    return this;
  }

   /**
   * The connector count.
   * @return connectors
  **/
  @Schema(required = true, description = "The connector count.")
  public Integer getConnectors() {
    return connectors;
  }

  public void setConnectors(Integer connectors) {
    this.connectors = connectors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProxyAllocationCounts proxyAllocationCounts = (ProxyAllocationCounts) o;
    return Objects.equals(this.allocations, proxyAllocationCounts.allocations) &&
        Objects.equals(this.connectors, proxyAllocationCounts.connectors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allocations, connectors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProxyAllocationCounts {\n");
    
    sb.append("    allocations: ").append(toIndentedString(allocations)).append("\n");
    sb.append("    connectors: ").append(toIndentedString(connectors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
