/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Information about the remote cluster for cross-cluster search.
 */
@Schema(description = "Information about the remote cluster for cross-cluster search.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class RemoteClusterInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("compatible")
  private Boolean compatible = null;

  @SerializedName("version")
  private String version = null;

  public RemoteClusterInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The remote Elasticsearch cluster deployment id
   * @return id
  **/
  @Schema(required = true, description = "The remote Elasticsearch cluster deployment id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RemoteClusterInfo compatible(Boolean compatible) {
    this.compatible = compatible;
    return this;
  }

   /**
   * Flag indicating whether the remote cluster version is compatible
   * @return compatible
  **/
  @Schema(required = true, description = "Flag indicating whether the remote cluster version is compatible")
  public Boolean isCompatible() {
    return compatible;
  }

  public void setCompatible(Boolean compatible) {
    this.compatible = compatible;
  }

  public RemoteClusterInfo version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Remote cluster Elasticsearch version
   * @return version
  **/
  @Schema(description = "Remote cluster Elasticsearch version")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoteClusterInfo remoteClusterInfo = (RemoteClusterInfo) o;
    return Objects.equals(this.id, remoteClusterInfo.id) &&
        Objects.equals(this.compatible, remoteClusterInfo.compatible) &&
        Objects.equals(this.version, remoteClusterInfo.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, compatible, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoteClusterInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    compatible: ").append(toIndentedString(compatible)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
