/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Returns the enrollment token that is used to securely start a new server with designated roles.
 */
@Schema(description = "Returns the enrollment token that is used to securely start a new server with designated roles.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class RequestEnrollmentTokenReply {
  @SerializedName("token")
  private String token = null;

  @SerializedName("token_id")
  private String tokenId = null;

  public RequestEnrollmentTokenReply token(String token) {
    this.token = token;
    return this;
  }

   /**
   * The requested token
   * @return token
  **/
  @Schema(required = true, description = "The requested token")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public RequestEnrollmentTokenReply tokenId(String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

   /**
   * An identifier for the requested token (if persistent) that can be used in listing and deletion
   * @return tokenId
  **/
  @Schema(description = "An identifier for the requested token (if persistent) that can be used in listing and deletion")
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestEnrollmentTokenReply requestEnrollmentTokenReply = (RequestEnrollmentTokenReply) o;
    return Objects.equals(this.token, requestEnrollmentTokenReply.token) &&
        Objects.equals(this.tokenId, requestEnrollmentTokenReply.tokenId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, tokenId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestEnrollmentTokenReply {\n");
    
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
