/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.FilterAssociation;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The configuration settings for IP filtering.
 */
@Schema(description = "The configuration settings for IP filtering.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class RulesetAssociations {
  @SerializedName("associations")
  private List<FilterAssociation> associations = new ArrayList<FilterAssociation>();

  @SerializedName("total_associations")
  private Integer totalAssociations = null;

  public RulesetAssociations associations(List<FilterAssociation> associations) {
    this.associations = associations;
    return this;
  }

  public RulesetAssociations addAssociationsItem(FilterAssociation associationsItem) {
    this.associations.add(associationsItem);
    return this;
  }

   /**
   * List of associations
   * @return associations
  **/
  @Schema(required = true, description = "List of associations")
  public List<FilterAssociation> getAssociations() {
    return associations;
  }

  public void setAssociations(List<FilterAssociation> associations) {
    this.associations = associations;
  }

  public RulesetAssociations totalAssociations(Integer totalAssociations) {
    this.totalAssociations = totalAssociations;
    return this;
  }

   /**
   * Total number of associations. This includes associations user doesn&#x27;t have permission to view.
   * @return totalAssociations
  **/
  @Schema(required = true, description = "Total number of associations. This includes associations user doesn't have permission to view.")
  public Integer getTotalAssociations() {
    return totalAssociations;
  }

  public void setTotalAssociations(Integer totalAssociations) {
    this.totalAssociations = totalAssociations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RulesetAssociations rulesetAssociations = (RulesetAssociations) o;
    return Objects.equals(this.associations, rulesetAssociations.associations) &&
        Objects.equals(this.totalAssociations, rulesetAssociations.totalAssociations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(associations, totalAssociations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RulesetAssociations {\n");
    
    sb.append("    associations: ").append(toIndentedString(associations)).append("\n");
    sb.append("    totalAssociations: ").append(toIndentedString(totalAssociations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
