/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The configuration for an Elasticsearch snapshot repository.
 */
@Schema(description = "The configuration for an Elasticsearch snapshot repository.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class SnapshotRepositoryConfiguration {
  @SerializedName("type")
  private String type = null;

  @SerializedName("settings")
  private Object settings = null;

  public SnapshotRepositoryConfiguration type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Repository type, (Currently supported: &#x27;s3&#x27;)
   * @return type
  **/
  @Schema(required = true, description = "Repository type, (Currently supported: 's3')")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public SnapshotRepositoryConfiguration settings(Object settings) {
    this.settings = settings;
    return this;
  }

   /**
   * Elasticsearch repository configuration settings JSON. See [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html) for more information
   * @return settings
  **/
  @Schema(required = true, description = "Elasticsearch repository configuration settings JSON. See [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html) for more information")
  public Object getSettings() {
    return settings;
  }

  public void setSettings(Object settings) {
    this.settings = settings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SnapshotRepositoryConfiguration snapshotRepositoryConfiguration = (SnapshotRepositoryConfiguration) o;
    return Objects.equals(this.type, snapshotRepositoryConfiguration.type) &&
        Objects.equals(this.settings, snapshotRepositoryConfiguration.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, settings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SnapshotRepositoryConfiguration {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
