/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.StackVersionTemplateFileHash;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The template information for an Elastic Stack version.
 */
@Schema(description = "The template information for an Elastic Stack version.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class StackVersionTemplateInfo {
  @SerializedName("template_version")
  private String templateVersion = null;

  @SerializedName("hashes")
  private List<StackVersionTemplateFileHash> hashes = null;

   /**
   * Template version
   * @return templateVersion
  **/
  @Schema(description = "Template version")
  public String getTemplateVersion() {
    return templateVersion;
  }

   /**
   * Relative paths of files with SHA-256 hashes that contains the template
   * @return hashes
  **/
  @Schema(description = "Relative paths of files with SHA-256 hashes that contains the template")
  public List<StackVersionTemplateFileHash> getHashes() {
    return hashes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StackVersionTemplateInfo stackVersionTemplateInfo = (StackVersionTemplateInfo) o;
    return Objects.equals(this.templateVersion, stackVersionTemplateInfo.templateVersion) &&
        Objects.equals(this.hashes, stackVersionTemplateInfo.hashes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateVersion, hashes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StackVersionTemplateInfo {\n");
    
    sb.append("    templateVersion: ").append(toIndentedString(templateVersion)).append("\n");
    sb.append("    hashes: ").append(toIndentedString(hashes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
