/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.StackVersionArchiveProcessingError;
import io.swagger.client.model.StackVersionConfig;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * The result from processing an archive of an Elastic Stack version.
 */
@Schema(description = "The result from processing an archive of an Elastic Stack version.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-10T16:33:30.970+05:30[Asia/Kolkata]")
public class StackVersionArchiveProcessingResult {
  @SerializedName("stacks")
  private List<StackVersionConfig> stacks = new ArrayList<StackVersionConfig>();

  @SerializedName("errors")
  private List<StackVersionArchiveProcessingError> errors = new ArrayList<StackVersionArchiveProcessingError>();

  public StackVersionArchiveProcessingResult stacks(List<StackVersionConfig> stacks) {
    this.stacks = stacks;
    return this;
  }

  public StackVersionArchiveProcessingResult addStacksItem(StackVersionConfig stacksItem) {
    this.stacks.add(stacksItem);
    return this;
  }

   /**
   * Get stacks
   * @return stacks
  **/
  @Schema(required = true, description = "")
  public List<StackVersionConfig> getStacks() {
    return stacks;
  }

  public void setStacks(List<StackVersionConfig> stacks) {
    this.stacks = stacks;
  }

  public StackVersionArchiveProcessingResult errors(List<StackVersionArchiveProcessingError> errors) {
    this.errors = errors;
    return this;
  }

  public StackVersionArchiveProcessingResult addErrorsItem(StackVersionArchiveProcessingError errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Errors occurred while processing the Elastic Stack pack. Key: stack version, Value: List of errors
   * @return errors
  **/
  @Schema(required = true, description = "Errors occurred while processing the Elastic Stack pack. Key: stack version, Value: List of errors")
  public List<StackVersionArchiveProcessingError> getErrors() {
    return errors;
  }

  public void setErrors(List<StackVersionArchiveProcessingError> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StackVersionArchiveProcessingResult stackVersionArchiveProcessingResult = (StackVersionArchiveProcessingResult) o;
    return Objects.equals(this.stacks, stackVersionArchiveProcessingResult.stacks) &&
        Objects.equals(this.errors, stackVersionArchiveProcessingResult.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stacks, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StackVersionArchiveProcessingResult {\n");
    
    sb.append("    stacks: ").append(toIndentedString(stacks)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
