/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BasicFailedReply;
import io.swagger.client.model.EmptyResponse;
import io.swagger.client.model.IdResponse;
import io.swagger.client.model.InstanceConfiguration;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlatformConfigurationInstancesApi
 */
@Ignore
public class PlatformConfigurationInstancesApiTest {

    private final PlatformConfigurationInstancesApi api = new PlatformConfigurationInstancesApi();

    /**
     * Create instance configuration
     *
     * Create instance configuration and return the auto-generated ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createInstanceConfigurationTest() throws ApiException {
        InstanceConfiguration body = null;
        IdResponse response = api.createInstanceConfiguration(body);

        // TODO: test validations
    }
    /**
     * Delete a instance configuration
     *
     * Delete the instance configuration with the given id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteInstanceConfigurationTest() throws ApiException {
        String id = null;
        Integer version = null;
        EmptyResponse response = api.deleteInstanceConfiguration(id, version);

        // TODO: test validations
    }
    /**
     * Get instance configuration
     *
     * Get instance configuration by id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInstanceConfigurationTest() throws ApiException {
        String id = null;
        Boolean showDeleted = null;
        InstanceConfiguration response = api.getInstanceConfiguration(id, showDeleted);

        // TODO: test validations
    }
    /**
     * Get instance configurations
     *
     * Get instance configurations.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInstanceConfigurationsTest() throws ApiException {
        Boolean showDeleted = null;
        List<InstanceConfiguration> response = api.getInstanceConfigurations(showDeleted);

        // TODO: test validations
    }
    /**
     * Set instance configuration
     *
     * Creates or updates an instance configuration.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setInstanceConfigurationTest() throws ApiException {
        InstanceConfiguration body = null;
        String id = null;
        Integer version = null;
        Boolean createOnly = null;
        IdResponse response = api.setInstanceConfiguration(body, id, version, createOnly);

        // TODO: test validations
    }
}
