/*
 * Elastic Cloud API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.BasicFailedReply;
import io.swagger.client.model.EmptyResponse;
import io.swagger.client.model.RepositoryConfig;
import io.swagger.client.model.RepositoryConfigs;
import io.swagger.client.model.SnapshotRepositoryConfiguration;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PlatformConfigurationSnapshotsApi {
    private ApiClient apiClient;

    public PlatformConfigurationSnapshotsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PlatformConfigurationSnapshotsApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for deleteSnapshotRepository
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call deleteSnapshotRepositoryCall(String repositoryName, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/platform/configuration/snapshots/repositories/{repository_name}"
            .replaceAll("\\{" + "repository_name" + "\\}", apiClient.escapeString(repositoryName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "apiKey", "basicAuth" };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call deleteSnapshotRepositoryValidateBeforeCall(String repositoryName, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'repositoryName' is set
        if (repositoryName == null) {
            throw new ApiException("Missing the required parameter 'repositoryName' when calling deleteSnapshotRepository(Async)");
        }
        
        com.squareup.okhttp.Call call = deleteSnapshotRepositoryCall(repositoryName, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Delete snapshot repository
     * Deletes the snapshot repository configuration.
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @return EmptyResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public EmptyResponse deleteSnapshotRepository(String repositoryName) throws ApiException {
        ApiResponse<EmptyResponse> resp = deleteSnapshotRepositoryWithHttpInfo(repositoryName);
        return resp.getData();
    }

    /**
     * Delete snapshot repository
     * Deletes the snapshot repository configuration.
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @return ApiResponse&lt;EmptyResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<EmptyResponse> deleteSnapshotRepositoryWithHttpInfo(String repositoryName) throws ApiException {
        com.squareup.okhttp.Call call = deleteSnapshotRepositoryValidateBeforeCall(repositoryName, null, null);
        Type localVarReturnType = new TypeToken<EmptyResponse>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Delete snapshot repository (asynchronously)
     * Deletes the snapshot repository configuration.
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deleteSnapshotRepositoryAsync(String repositoryName, final ApiCallback<EmptyResponse> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deleteSnapshotRepositoryValidateBeforeCall(repositoryName, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<EmptyResponse>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getSnapshotRepositories
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getSnapshotRepositoriesCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/platform/configuration/snapshots/repositories";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "apiKey", "basicAuth" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getSnapshotRepositoriesValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        com.squareup.okhttp.Call call = getSnapshotRepositoriesCall(progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get snapshot repositories
     * Retrieves a list of available snapshot repository configurations. To access the configuration contents, you must have privileged permissions.
     * @return RepositoryConfigs
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public RepositoryConfigs getSnapshotRepositories() throws ApiException {
        ApiResponse<RepositoryConfigs> resp = getSnapshotRepositoriesWithHttpInfo();
        return resp.getData();
    }

    /**
     * Get snapshot repositories
     * Retrieves a list of available snapshot repository configurations. To access the configuration contents, you must have privileged permissions.
     * @return ApiResponse&lt;RepositoryConfigs&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<RepositoryConfigs> getSnapshotRepositoriesWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = getSnapshotRepositoriesValidateBeforeCall(null, null);
        Type localVarReturnType = new TypeToken<RepositoryConfigs>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get snapshot repositories (asynchronously)
     * Retrieves a list of available snapshot repository configurations. To access the configuration contents, you must have privileged permissions.
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getSnapshotRepositoriesAsync(final ApiCallback<RepositoryConfigs> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getSnapshotRepositoriesValidateBeforeCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<RepositoryConfigs>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getSnapshotRepository
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getSnapshotRepositoryCall(String repositoryName, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/platform/configuration/snapshots/repositories/{repository_name}"
            .replaceAll("\\{" + "repository_name" + "\\}", apiClient.escapeString(repositoryName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "apiKey", "basicAuth" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getSnapshotRepositoryValidateBeforeCall(String repositoryName, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'repositoryName' is set
        if (repositoryName == null) {
            throw new ApiException("Missing the required parameter 'repositoryName' when calling getSnapshotRepository(Async)");
        }
        
        com.squareup.okhttp.Call call = getSnapshotRepositoryCall(repositoryName, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get snapshot repository
     * Retrieves the snapshot repository configuration. To access the configuration contents, you must have privileged permissions.
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @return RepositoryConfig
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public RepositoryConfig getSnapshotRepository(String repositoryName) throws ApiException {
        ApiResponse<RepositoryConfig> resp = getSnapshotRepositoryWithHttpInfo(repositoryName);
        return resp.getData();
    }

    /**
     * Get snapshot repository
     * Retrieves the snapshot repository configuration. To access the configuration contents, you must have privileged permissions.
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @return ApiResponse&lt;RepositoryConfig&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<RepositoryConfig> getSnapshotRepositoryWithHttpInfo(String repositoryName) throws ApiException {
        com.squareup.okhttp.Call call = getSnapshotRepositoryValidateBeforeCall(repositoryName, null, null);
        Type localVarReturnType = new TypeToken<RepositoryConfig>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get snapshot repository (asynchronously)
     * Retrieves the snapshot repository configuration. To access the configuration contents, you must have privileged permissions.
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getSnapshotRepositoryAsync(String repositoryName, final ApiCallback<RepositoryConfig> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getSnapshotRepositoryValidateBeforeCall(repositoryName, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<RepositoryConfig>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for setSnapshotRepository
     * @param body The Elasticsearch snapshot repository configuration (required)
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @param version Checks for conflicts against the metadata version, then returns the value in the &#x60;x-cloud-resource-version&#x60; header. (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call setSnapshotRepositoryCall(SnapshotRepositoryConfiguration body, String repositoryName, Integer version, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/platform/configuration/snapshots/repositories/{repository_name}"
            .replaceAll("\\{" + "repository_name" + "\\}", apiClient.escapeString(repositoryName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (version != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("version", version));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "*/*"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "apiKey", "basicAuth" };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call setSnapshotRepositoryValidateBeforeCall(SnapshotRepositoryConfiguration body, String repositoryName, Integer version, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'body' is set
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling setSnapshotRepository(Async)");
        }
        // verify the required parameter 'repositoryName' is set
        if (repositoryName == null) {
            throw new ApiException("Missing the required parameter 'repositoryName' when calling setSnapshotRepository(Async)");
        }
        
        com.squareup.okhttp.Call call = setSnapshotRepositoryCall(body, repositoryName, version, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Set snapshot repository
     * Creates or updates the snapshot repository configuration.
     * @param body The Elasticsearch snapshot repository configuration (required)
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @param version Checks for conflicts against the metadata version, then returns the value in the &#x60;x-cloud-resource-version&#x60; header. (optional)
     * @return RepositoryConfig
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public RepositoryConfig setSnapshotRepository(SnapshotRepositoryConfiguration body, String repositoryName, Integer version) throws ApiException {
        ApiResponse<RepositoryConfig> resp = setSnapshotRepositoryWithHttpInfo(body, repositoryName, version);
        return resp.getData();
    }

    /**
     * Set snapshot repository
     * Creates or updates the snapshot repository configuration.
     * @param body The Elasticsearch snapshot repository configuration (required)
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @param version Checks for conflicts against the metadata version, then returns the value in the &#x60;x-cloud-resource-version&#x60; header. (optional)
     * @return ApiResponse&lt;RepositoryConfig&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<RepositoryConfig> setSnapshotRepositoryWithHttpInfo(SnapshotRepositoryConfiguration body, String repositoryName, Integer version) throws ApiException {
        com.squareup.okhttp.Call call = setSnapshotRepositoryValidateBeforeCall(body, repositoryName, version, null, null);
        Type localVarReturnType = new TypeToken<RepositoryConfig>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Set snapshot repository (asynchronously)
     * Creates or updates the snapshot repository configuration.
     * @param body The Elasticsearch snapshot repository configuration (required)
     * @param repositoryName The name of the snapshot repository configuration. (required)
     * @param version Checks for conflicts against the metadata version, then returns the value in the &#x60;x-cloud-resource-version&#x60; header. (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call setSnapshotRepositoryAsync(SnapshotRepositoryConfiguration body, String repositoryName, Integer version, final ApiCallback<RepositoryConfig> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = setSnapshotRepositoryValidateBeforeCall(body, repositoryName, version, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<RepositoryConfig>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
